## Load libraries

```{r, message=FALSE}
library(caret)
library(dplyr)
library(randomForest)
library(readr)
```

## Load the data

```{r, message=FALSE}
url <- "https://github.com/rosborne132/rNotebook/raw/main/final-project/data/Quote_Data.csv.zip"

# Download and unzip the CSV file ============
temp <- tempfile()
download.file(url, temp)
unzip(temp, exdir = tempdir())
csv_file <- list.files(tempdir(), pattern = "\\.csv$", full.names = TRUE)
quote_data <- read_csv(
  csv_file,
  show_col_types = FALSE,
  col_select = c(
    "ANNUALPREMIUM",
    "MONTHLYPREMIUMINSTALMENT",
    "PETAGEYEARS",
    "PETGENDER",
    "SPECIES",
  )
)
```

## Prepare the data

```{r, message=FALSE}
# Clean up the data =========================
quote_data$MONTHLYPREMIUMINSTALMENT <- as.numeric(
  gsub("£", "", quote_data$MONTHLYPREMIUMINSTALMENT)
)

# Prepare the data for training
model_data <- quote_data %>%
  select(
    ANNUALPREMIUM,
    PETAGEYEARS,
    PETGENDER,
    SPECIES,
    MONTHLYPREMIUMINSTALMENT
  ) %>%
  na.omit() %>%
  filter(is.finite(MONTHLYPREMIUMINSTALMENT))

model_data$PETGENDER <- as.factor(model_data$PETGENDER)
model_data$SPECIES <- as.factor(model_data$SPECIES)
```


## Train the model

### Annual Premium Model

```{r, message=FALSE}
# Train the model
train_control <- trainControl(method = "cv", number = 10)
ap_model <- train(
  ANNUALPREMIUM ~ PETAGEYEARS + PETGENDER + SPECIES,
  data = model_data,
  method = "rf",
  trControl = train_control
)

# Save the model to a file
saveRDS(model, "app/src/www/models/ap_model.rds")
```

### Monthly Premium Installments Model

```{r, message=FALSE}
# Train the model
train_control <- trainControl(method = "cv", number = 10)
mpi_model <- train(
  MONTHLYPREMIUMINSTALMENT ~ PETAGEYEARS + PETGENDER + SPECIES,
  data = model_data,
  method = "rf",
  trControl = train_control
)

# Save the model to a file
saveRDS(mpi_model, "app/src/www/models/mpi_model.rds")
```
